 name: RoodCoreReloaded
 version: 1.0
 description: RoodCoreReloaded
 # We could place every author in the authors list, but chose not to for illustrative purposes
 # Also, having an author distinguishes that person as the project lead, and ensures their 
 # name is displayed first
 author: cooltimmetje
 main: me.cooltimmetje.RoodCoreReloaded.Main
 commands:
   tp:
      description: A better TP command.
      permission: rcr.tp
   silenttp:
      description: You don't have to know this...
   doomsday:
      description: idk?
   transmute:
      description: open transmute system
   swaggergear:
      description: gives swag gear